### ISSUE TITLE
How many requests can I send back to back ? 

### ISSUE THREAD

**Issue by adityaspt** [meetDeveloper/googleDictionaryAPI#74] opened 2020-11-05 16:29 UTC
When I try to get a lot of words back to back (more than 15words, i want to get 1000s of words at a time)
i catch this exception
System.Net.WebException: The remote server returned an error: (429) Too Many Requests

How much would be the Host server capacity?

I will try to increase the interval between requests by using Thread.Sleep(n)

Also any solution to this issue would be appreciated.

**Comment by meetDeveloper** [comment] 2020-11-16 22:10
Marking this duplicate of #73. Will track this there.

**Closed by meetDeveloper** 2020-11-16 22:10 UTC
